# Baseline Balanced CICIoT2023 — DNN, Without Feature Augmentation and Without Optuna

## 1. Imports, dataset path, and reproducibility

In [1]:
# ============================================================
# Imports and fixed experiment seed
# ============================================================
import gc
import json
import os
import platform
import random
import time
from collections import Counter
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    multilabel_confusion_matrix,
    precision_recall_fscore_support,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense, Dropout, GRU, Input, LSTM
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.optimizers import Adam

# ============================================================
# Pre-generated CICIoT2023 train/validation/test partitions
# ============================================================
AUGMENTED_DATA_DIRECTORY = Path(
    r"/kaggle/input/datasets/zerukifle/ciciot2023-fa-multirun"
)

TRAIN_FILE = (
    AUGMENTED_DATA_DIRECTORY
    / "CICIoT2023_Augmented_Train.csv"
)
VALIDATION_FILE = (
    AUGMENTED_DATA_DIRECTORY
    / "CICIoT2023_Augmented_Validation.csv"
)
TEST_FILE = (
    AUGMENTED_DATA_DIRECTORY
    / "CICIoT2023_Augmented_Test.csv"
)

# Retained for compatibility with the existing experiment metadata.
DATASET_PATH = AUGMENTED_DATA_DIRECTORY

SEED = 42
RANDOM_STATE = SEED
os.environ["PYTHONHASHSEED"] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

print("Fixed experiment seed:", SEED)
print("Training file:", TRAIN_FILE)
print("Validation file:", VALIDATION_FILE)
print("Test file:", TEST_FILE)

Fixed experiment seed: 42
Training file: /kaggle/input/datasets/zerukifle/ciciot2023-fa-multirun/CICIoT2023_Augmented_Train.csv
Validation file: /kaggle/input/datasets/zerukifle/ciciot2023-fa-multirun/CICIoT2023_Augmented_Validation.csv
Test file: /kaggle/input/datasets/zerukifle/ciciot2023-fa-multirun/CICIoT2023_Augmented_Test.csv

In [2]:
# ============================================================
# Load pre-generated CICIoT2023 partitions
# ============================================================
for file_path in [
    TRAIN_FILE,
    VALIDATION_FILE,
    TEST_FILE,
]:
    if not file_path.is_file():
        raise FileNotFoundError(
            f"Required CICIoT2023 partition not found: {file_path}"
        )

train_data = pd.read_csv(TRAIN_FILE)
validation_data = pd.read_csv(VALIDATION_FILE)
test_data = pd.read_csv(TEST_FILE)

LABEL_COLUMN = "label"

for dataset_name, dataset in {
    "Training": train_data,
    "Validation": validation_data,
    "Test": test_data,
}.items():
    if LABEL_COLUMN not in dataset.columns:
        raise KeyError(
            f"'{LABEL_COLUMN}' was not found in the {dataset_name} partition."
        )

print(f"Training data:   {train_data.shape}")
print(f"Validation data: {validation_data.shape}")
print(f"Test data:       {test_data.shape}")

display(train_data.head())

Training data:   (354737, 36)
Validation data: (118246, 36)
Test data:       (118246, 36)

,flow_duration,Header_Length,Protocol Type,Duration,Rate,Drate,fin_flag_number,syn_flag_number,psh_flag_number,ack_flag_number,...,Max,AVG,Tot size,IAT,Covariance,Variance,IF_Anomaly_Score,AE_Anomaly_Score,SUOD_Anomaly_Score,label
0,0.244612,38791.0,17.00,64.00,3202.228500,0.0,0.0,0.0,0.0,0.0,...,50.00,50.00000,50.00,83102420.0,0.000000,0.00,0.275168,0.004453,-0.277339,DDoS
1,0.014093,5675.0,17.00,64.00,8785.439000,0.0,0.0,0.0,0.0,0.0,...,50.00,50.00000,50.00,83123740.0,0.000000,0.00,0.283322,0.004197,-0.291433,DDoS
2,0.000000,0.0,47.00,64.00,218.863710,0.0,0.0,0.0,0.0,0.0,...,592.00,592.00000,592.00,83698550.0,0.000000,0.00,0.161012,0.083652,0.648249,Mirai
3,0.000000,54.0,6.00,64.00,3.887012,0.0,0.0,0.0,0.0,0.0,...,54.00,54.00000,54.00,83064136.0,0.000000,0.00,0.319291,0.000523,-0.766263,DDoS
4,0.000000,0.0,0.99,63.36,5.231067,0.0,0.0,0.0,0.0,0.0,...,43.98,42.13838,42.18,83150650.0,2.315749,0.11,0.216951,0.004651,0.238320,DDoS

## 2. Drop Anomaly Scores

In [3]:
# ============================================================
# Feature-target separation and validation
# ============================================================
anomaly_score_columns = [
    "IF_Anomaly_Score",
    "AE_Anomaly_Score",
    "SUOD_Anomaly_Score",
]

for dataset_name, dataset in {
    "Training": train_data,
    "Validation": validation_data,
    "Test": test_data,
}.items():
    missing_anomaly_features = [
        feature
        for feature in anomaly_score_columns
        if feature not in dataset.columns
    ]

    if missing_anomaly_features:
        raise KeyError(
            f"{dataset_name} partition is missing anomaly-score features: "
            f"{missing_anomaly_features}"
        )

# ============================================================
# Remove anomaly-score features for the No-FA experiment
# ============================================================
train_data = train_data.drop(
    columns=anomaly_score_columns
)
validation_data = validation_data.drop(
    columns=anomaly_score_columns
)
test_data = test_data.drop(
    columns=anomaly_score_columns
)

feature_columns = [
    column for column in train_data.columns
    if column != LABEL_COLUMN
]

for dataset_name, dataset in {
    "Validation": validation_data,
    "Test": test_data,
}.items():
    current_features = [
        column for column in dataset.columns
        if column != LABEL_COLUMN
    ]

    if current_features != feature_columns:
        raise ValueError(
            f"{dataset_name} feature columns/order do not match training."
        )

X_train_raw = train_data[feature_columns].copy()
X_val_raw = validation_data[feature_columns].copy()
X_test_raw = test_data[feature_columns].copy()

y_train_raw = (
    train_data[LABEL_COLUMN]
    .astype(str)
    .str.strip()
)
y_val_raw = (
    validation_data[LABEL_COLUMN]
    .astype(str)
    .str.strip()
)
y_test_raw = (
    test_data[LABEL_COLUMN]
    .astype(str)
    .str.strip()
)

for dataset_name, labels in {
    "Training": y_train_raw,
    "Validation": y_val_raw,
    "Test": y_test_raw,
}.items():
    if labels.isna().any() or labels.eq("").any():
        raise ValueError(
            f"{dataset_name} target labels contain missing or empty values."
        )

for dataset_name, feature_data in {
    "Training": X_train_raw,
    "Validation": X_val_raw,
    "Test": X_test_raw,
}.items():
    non_numeric_columns = (
        feature_data
        .select_dtypes(exclude=np.number)
        .columns
        .tolist()
    )

    if non_numeric_columns:
        raise TypeError(
            f"{dataset_name} contains non-numeric feature columns: "
            f"{non_numeric_columns}"
        )

    if not np.isfinite(
        feature_data.to_numpy(dtype=np.float64)
    ).all():
        raise ValueError(
            f"{dataset_name} features contain missing or infinite values."
        )

# Preserve row positions within each pre-generated partition so that
# the existing artifact-saving structure remains unchanged.
train_indices = X_train_raw.index.to_numpy(copy=True)
validation_indices = X_val_raw.index.to_numpy(copy=True)
test_indices = X_test_raw.index.to_numpy(copy=True)

X_train_raw = X_train_raw.reset_index(drop=True)
X_val_raw = X_val_raw.reset_index(drop=True)
X_test_raw = X_test_raw.reset_index(drop=True)

y_train_raw = y_train_raw.reset_index(drop=True)
y_val_raw = y_val_raw.reset_index(drop=True)
y_test_raw = y_test_raw.reset_index(drop=True)

print("Original training shape:", X_train_raw.shape)
print("Validation shape:", X_val_raw.shape)
print("Test shape:", X_test_raw.shape)

del train_data, validation_data, test_data

Original training shape: (354737, 32)
Validation shape: (118246, 32)
Test shape: (118246, 32)

In [4]:
# ============================================================
# Fit label encoding on training labels only, then reuse it.
# ============================================================
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train_raw)

training_classes = set(label_encoder.classes_)
unknown_val = set(y_val_raw.unique()) - training_classes
unknown_test = set(y_test_raw.unique()) - training_classes
if unknown_val or unknown_test:
    raise ValueError(
        "Validation/test contain classes absent from training: "
        f"validation={unknown_val}, test={unknown_test}"
    )

y_val = label_encoder.transform(y_val_raw)
y_test = label_encoder.transform(y_test_raw)
number_of_classes = len(label_encoder.classes_)

print("Class mapping:")
for code_value, class_name in enumerate(label_encoder.classes_):
    print(f"  {code_value}: {class_name}")


def show_distribution(labels, name):
    counts = pd.Series(labels).value_counts().sort_index()
    counts.index = [label_encoder.classes_[int(i)] for i in counts.index]
    normalized = counts / counts.sum()
    table = pd.DataFrame({"Count": counts, "Proportion": normalized})
    print(f"\n{name}")
    display(table)

show_distribution(y_train, "Original training distribution")
show_distribution(y_val, "Validation distribution")
show_distribution(y_test, "Test distribution")

Class mapping:
  0: Benign
  1: BruteForce
  2: DDoS
  3: DoS
  4: Mirai
  5: Recon
  6: Spoofing
  7: Web

Original training distribution

             Count  Proportion
Benign        8248    0.023251
BruteForce     100    0.000282
DDoS        258100    0.727581
DoS          61405    0.173100
Mirai        20231    0.057031
Recon         2736    0.007713
Spoofing      3729    0.010512
Web            188    0.000530

Validation distribution

            Count  Proportion
Benign       2750    0.023257
BruteForce     33    0.000279
DDoS        86033    0.727576
DoS         20468    0.173097
Mirai        6744    0.057034
Recon         912    0.007713
Spoofing     1243    0.010512
Web            63    0.000533

Test distribution

            Count  Proportion
Benign       2749    0.023248
BruteForce     33    0.000279
DDoS        86034    0.727585
DoS         20469    0.173105
Mirai        6744    0.057034
Recon         912    0.007713
Spoofing     1243    0.010512
Web            62    0.000524

## 3. Training-only SMOTE and standardization

In [5]:
# ============================================================
# Preserve the original baseline SMOTE target counts.
# SMOTE is applied only to the training partition.
# ============================================================
target_class_counts = {
    0: 8248 + 1752,
    1: 100 + 9900,
    5: 2736 + 7264,
    6: 3729 + 6271,
    7: 188 + 9812,
}

original_training_counts = Counter(y_train)
print("Training distribution before SMOTE:", original_training_counts)

# Validate the requested strategy before fitting SMOTE.
for class_code, requested_count in target_class_counts.items():
    if class_code not in original_training_counts:
        raise ValueError(f"SMOTE target class {class_code} is absent from training data.")
    if requested_count < original_training_counts[class_code]:
        raise ValueError(
            f"SMOTE target for class {class_code} ({requested_count}) is smaller than "
            f"its current training count ({original_training_counts[class_code]})."
        )

smote = SMOTE(
    sampling_strategy=target_class_counts,
    random_state=SEED,
)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train_raw,
    y_train,
)

print("Training distribution after SMOTE:", Counter(y_train_resampled))
print("Resampled training shape:", X_train_resampled.shape)

Training distribution before SMOTE: Counter({np.int64(2): 258100, np.int64(3): 61405, np.int64(4): 20231, np.int64(0): 8248, np.int64(6): 3729, np.int64(5): 2736, np.int64(7): 188, np.int64(1): 100})
Training distribution after SMOTE: Counter({np.int64(2): 258100, np.int64(3): 61405, np.int64(4): 20231, np.int64(6): 10000, np.int64(0): 10000, np.int64(5): 10000, np.int64(7): 10000, np.int64(1): 10000})
Resampled training shape: (389736, 32)

In [6]:
# ============================================================
# Fit StandardScaler on the SMOTE-resampled training set only.
# ============================================================
classifier_scaler = StandardScaler()

X_train_scaled = classifier_scaler.fit_transform(
    X_train_resampled
).astype(np.float32)

X_val_scaled = classifier_scaler.transform(
    X_val_raw
).astype(np.float32)

X_test_scaled = classifier_scaler.transform(
    X_test_raw
).astype(np.float32)

for partition_name, values in {
    "resampled training": X_train_scaled,
    "validation": X_val_scaled,
    "test": X_test_scaled,
}.items():
    if not np.isfinite(values).all():
        raise ValueError(f"Scaled {partition_name} contains invalid values.")

print(f"Resampled training mean after scaling: {X_train_scaled.mean():.6f}")
print(f"Resampled training standard deviation after scaling: {X_train_scaled.std():.6f}")
print("Scaled training shape:", X_train_scaled.shape)
print("Scaled validation shape:", X_val_scaled.shape)
print("Scaled test shape:", X_test_scaled.shape)

Resampled training mean after scaling: 0.000000
Resampled training standard deviation after scaling: 1.000000
Scaled training shape: (389736, 32)
Scaled validation shape: (118246, 32)
Scaled test shape: (118246, 32)

## 4. Fixed baseline configuration — no Optuna

In [7]:
# ============================================================
# Fixed baseline settings from the uploaded notebook.
# No Optuna and no pre-stored optimized hyperparameters.
# ============================================================
RUN_SEEDS = [42, 43, 44, 45, 46]
N_FINAL_RUNS = len(RUN_SEEDS)

N_WARMUP_RUNS = 3
N_BENCHMARK_RUNS = 5

BASELINE_HYPERPARAMETERS = {
    "hidden_units_1": 64,
    "hidden_units_2": 32,
    "dropout_rate": 0.2,
    "learning_rate": 0.001,
    "l2_regularization": 1e-4,
    "epochs": 100,
    "batch_size": 64,
    "shuffle": True,
    "early_stopping": {
        "monitor": "val_loss",
        "patience": 10,
        "min_delta": 0.0,
        "restore_best_weights": True,
    },
}

print("Final training seeds:", RUN_SEEDS)
print("Fixed baseline hyperparameters:")
print(json.dumps(BASELINE_HYPERPARAMETERS, indent=2))

Final training seeds: [42, 43, 44, 45, 46]
Fixed baseline hyperparameters:
{
  "hidden_units_1": 64,
  "hidden_units_2": 32,
  "dropout_rate": 0.2,
  "learning_rate": 0.001,
  "l2_regularization": 0.0001,
  "epochs": 100,
  "batch_size": 64,
  "shuffle": true,
  "early_stopping": {
    "monitor": "val_loss",
    "patience": 10,
    "min_delta": 0.0,
    "restore_best_weights": true
  }
}

## 5. Evaluation utilities

In [8]:
# ============================================================
# Reproducibility, metrics, timing, and output utilities
# ============================================================
def set_final_run_seed(seed):
    """Reset only model-training random states for one independent run."""
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.keras.utils.set_random_seed(seed)


try:
    tf.config.experimental.enable_op_determinism()
    print("TensorFlow deterministic operations enabled.")
except (AttributeError, RuntimeError):
    print("TensorFlow deterministic-operation control is unavailable.")


def make_early_stopping():
    cfg = BASELINE_HYPERPARAMETERS["early_stopping"]
    return EarlyStopping(
        monitor=cfg["monitor"],
        patience=cfg["patience"],
        min_delta=cfg["min_delta"],
        restore_best_weights=cfg["restore_best_weights"],
        verbose=1,
    )


def benchmark_full_test_prediction(model, X_input):
    """3 warm-ups followed by 10 measured full-test predictions."""
    warmup_size = min(1024, len(X_input))
    for _ in range(N_WARMUP_RUNS):
        model.predict(X_input[:warmup_size], verbose=0)

    measured_times = []
    probabilities = None
    for _ in range(N_BENCHMARK_RUNS):
        start_time = time.perf_counter()
        probabilities = model.predict(X_input, verbose=0)
        measured_times.append(time.perf_counter() - start_time)

    mean_inference_time = float(np.mean(measured_times))
    return probabilities, {
        "Inference_Time_s": mean_inference_time,
        "Latency_ms_per_sample": mean_inference_time / len(X_input) * 1000.0,
        "Throughput_samples_per_s": len(X_input) / mean_inference_time,
    }


def calculate_fpr_metrics(y_true, y_pred, labels):
    matrices = multilabel_confusion_matrix(y_true, y_pred, labels=labels)
    per_class_fpr, false_positives, true_negatives = [], [], []

    for matrix in matrices:
        tn, fp, fn, tp = matrix.ravel()
        denominator = fp + tn
        per_class_fpr.append(fp / denominator if denominator else 0.0)
        false_positives.append(fp)
        true_negatives.append(tn)

    per_class_fpr = np.asarray(per_class_fpr, dtype=float)
    false_positives = np.asarray(false_positives, dtype=float)
    true_negatives = np.asarray(true_negatives, dtype=float)
    supports = np.asarray([(y_true == label).sum() for label in labels], dtype=float)
    overall_denominator = false_positives.sum() + true_negatives.sum()

    return {
        "FPR_macro": float(per_class_fpr.mean()),
        "FPR_micro_overall": float(
            false_positives.sum() / overall_denominator
            if overall_denominator else 0.0
        ),
        "FPR_weighted": float(np.average(per_class_fpr, weights=supports)),
    }, per_class_fpr, matrices


def calculate_test_metrics(y_true, y_pred, probabilities, labels):
    metrics = {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision_macro": precision_score(
            y_true, y_pred, labels=labels, average="macro", zero_division=0
        ),
        "Recall_macro": recall_score(
            y_true, y_pred, labels=labels, average="macro", zero_division=0
        ),
        "F1_macro": f1_score(
            y_true, y_pred, labels=labels, average="macro", zero_division=0
        ),
        "Precision_weighted": precision_score(
            y_true, y_pred, labels=labels, average="weighted", zero_division=0
        ),
        "Recall_weighted": recall_score(
            y_true, y_pred, labels=labels, average="weighted", zero_division=0
        ),
        "F1_weighted": f1_score(
            y_true, y_pred, labels=labels, average="weighted", zero_division=0
        ),
        "MCC": matthews_corrcoef(y_true, y_pred),
    }

    try:
        metrics["ROC_AUC_macro_OvR"] = roc_auc_score(
            y_true,
            probabilities,
            labels=labels,
            average="macro",
            multi_class="ovr",
        )
    except ValueError as error:
        metrics["ROC_AUC_macro_OvR"] = np.nan
        print("Macro ROC-AUC could not be calculated:", error)

    fpr_summary, per_class_fpr, class_matrices = calculate_fpr_metrics(
        y_true, y_pred, labels
    )
    metrics.update(fpr_summary)
    return metrics, per_class_fpr, class_matrices


def format_mean_sd(mean_value, sd_value, decimals=6, percentage=False):
    if pd.isna(mean_value):
        return "NA"
    multiplier = 100.0 if percentage else 1.0
    mean_value *= multiplier
    sd_value *= multiplier
    if pd.isna(sd_value):
        return f"{mean_value:.{decimals}f} ± NA"
    return f"{mean_value:.{decimals}f} ± {sd_value:.{decimals}f}"


def save_confusion_matrix_outputs(y_true, y_pred, output_stem):
    matrix = confusion_matrix(
        y_true, y_pred, labels=np.arange(number_of_classes)
    )
    matrix_df = pd.DataFrame(
        matrix,
        index=label_encoder.classes_,
        columns=label_encoder.classes_,
    )
    matrix_df.index.name = "True_Label"
    matrix_df.columns.name = "Predicted_Label"
    matrix_df.to_csv(f"{output_stem}.csv")

    fig, ax = plt.subplots(figsize=(7.5, 6.0))
    image = ax.imshow(matrix)
    fig.colorbar(image, ax=ax)
    ax.set_xticks(np.arange(number_of_classes))
    ax.set_yticks(np.arange(number_of_classes))
    ax.set_xticklabels(label_encoder.classes_, rotation=45, ha="right")
    ax.set_yticklabels(label_encoder.classes_)
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")

    threshold = matrix.max() / 2.0 if matrix.size else 0
    for row in range(matrix.shape[0]):
        for col in range(matrix.shape[1]):
            ax.text(
                col,
                row,
                f"{matrix[row, col]:d}",
                ha="center",
                va="center",
                color="white" if matrix[row, col] > threshold else "black",
                fontsize=8,
            )

    fig.tight_layout()
    fig.savefig(f"{output_stem}.pdf", bbox_inches="tight")
    fig.savefig(f"{output_stem}.png", dpi=600, bbox_inches="tight")
    plt.close(fig)


def build_per_class_table(y_true, y_pred, labels, per_class_fpr, class_matrices):
    precision, recall, f1, support = precision_recall_fscore_support(
        y_true,
        y_pred,
        labels=labels,
        zero_division=0,
    )
    rows = []
    for idx, label in enumerate(labels):
        tn, fp, fn, tp = class_matrices[idx].ravel()
        rows.append({
            "Class_Code": int(label),
            "Class": str(label_encoder.classes_[label]),
            "Precision": float(precision[idx]),
            "Recall": float(recall[idx]),
            "F1": float(f1[idx]),
            "FPR": float(per_class_fpr[idx]),
            "TP": int(tp),
            "TN": int(tn),
            "FP": int(fp),
            "FN": int(fn),
            "Support": int(support[idx]),
        })
    return pd.DataFrame(rows)

TensorFlow deterministic operations enabled.

## 5. Fixed DNN baseline architecture

In [9]:
num_features = X_train_scaled.shape[1]
X_train_input = X_train_scaled
X_val_input = X_val_scaled
X_test_input = X_test_scaled


def build_baseline_model():
    p = BASELINE_HYPERPARAMETERS
    reg = regularizers.l2(p["l2_regularization"])
    model = Sequential(name="Baseline_DNN")
    model.add(Input(shape=(num_features,)))
    model.add(Dense(p["hidden_units_1"], activation="relu", kernel_regularizer=reg))
    model.add(Dropout(p["dropout_rate"]))
    model.add(Dense(p["hidden_units_2"], activation="relu", kernel_regularizer=reg))
    model.add(Dropout(p["dropout_rate"]))
    model.add(Dense(number_of_classes, activation="softmax", kernel_regularizer=reg))
    model.compile(
        optimizer=Adam(learning_rate=p["learning_rate"]),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model

print("DNN input shapes:", X_train_input.shape, X_val_input.shape, X_test_input.shape)

DNN input shapes: (389736, 32) (118246, 32) (118246, 32)

## 6. Five-seed DNN training and evaluation

In [10]:
# ============================================================
# Five independent final-training runs: seeds 42-46
# Data split, SMOTE output, scaler, architecture, and settings stay fixed.
# ============================================================
MODEL_NAME = "DNN"
OUTPUT_DIRECTORY = Path.cwd() / "Baseline_Balanced_Without_FA_CICIoT2023_DNN_5_seed_results"
ARTIFACT_DIRECTORY = OUTPUT_DIRECTORY / "reusable_artifacts"
OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
ARTIFACT_DIRECTORY.mkdir(parents=True, exist_ok=True)

# Save reusable fixed preprocessing/configuration once.
joblib.dump(classifier_scaler, ARTIFACT_DIRECTORY / "standard_scaler.joblib")
joblib.dump(label_encoder, ARTIFACT_DIRECTORY / "label_encoder.joblib")
with (ARTIFACT_DIRECTORY / "feature_columns.json").open("w", encoding="utf-8") as f:
    json.dump(feature_columns, f, indent=2)
with (ARTIFACT_DIRECTORY / "smote_sampling_strategy.json").open("w", encoding="utf-8") as f:
    json.dump({str(k): int(v) for k, v in target_class_counts.items()}, f, indent=2)
np.savez_compressed(
    ARTIFACT_DIRECTORY / "fixed_split_indices.npz",
    train=train_indices,
    validation=validation_indices,
    test=test_indices,
)

experiment_config = {
    "Experiment": "Baseline Balanced CICIoT2023 without feature augmentation and without Optuna",
    "Model": MODEL_NAME,
    "Dataset_Path": str(DATASET_PATH),
    "Split_Random_State": int(SEED),
    "Split": {"Train": 0.60, "Validation": 0.20, "Test": 0.20},
    "SMOTE_Random_State": int(SEED),
    "SMOTE_Target_Class_Counts": {str(k): int(v) for k, v in target_class_counts.items()},
    "Run_Seeds": RUN_SEEDS,
    "Hyperparameters": BASELINE_HYPERPARAMETERS,
    "Inference_Protocol": {
        "Warmup_Runs": N_WARMUP_RUNS,
        "Measured_Runs": N_BENCHMARK_RUNS,
        "Timer": "time.perf_counter",
    },
}
with (ARTIFACT_DIRECTORY / "experiment_config.json").open("w", encoding="utf-8") as f:
    json.dump(experiment_config, f, indent=2)

labels = np.arange(number_of_classes)
run_rows = []
per_class_rows = []
representative_candidates = []

for run_number, seed in enumerate(RUN_SEEDS, start=1):
    print(f"\n{'='*18} {MODEL_NAME} run {run_number}/5 — seed {seed} {'='*18}")

    seed_directory = OUTPUT_DIRECTORY / f"{MODEL_NAME}_Seed_{run_number}"
    seed_directory.mkdir(parents=True, exist_ok=True)

    tf.keras.backend.clear_session()
    set_final_run_seed(seed)
    model = build_baseline_model()
    early_stop = make_early_stopping()

    start_training = time.perf_counter()
    history = model.fit(
        X_train_input,
        y_train_resampled,
        validation_data=(X_val_input, y_val),
        epochs=BASELINE_HYPERPARAMETERS["epochs"],
        batch_size=BASELINE_HYPERPARAMETERS["batch_size"],
        shuffle=BASELINE_HYPERPARAMETERS["shuffle"],
        callbacks=[early_stop],
        verbose=1,
    )
    training_time = time.perf_counter() - start_training

    # Validation macro F1 for run diagnostics only.
    val_probabilities = model.predict(X_val_input, verbose=0)
    val_predictions = np.argmax(val_probabilities, axis=1)
    validation_macro_f1 = f1_score(
        y_val, val_predictions, average="macro", zero_division=0
    )

    # Fixed timing protocol also returns final full-test probabilities.
    test_probabilities, timing_metrics = benchmark_full_test_prediction(
        model, X_test_input
    )
    test_predictions = np.argmax(test_probabilities, axis=1)

    test_loss = float(model.evaluate(X_test_input, y_test, verbose=0)[0])
    test_metrics, per_class_fpr, class_matrices = calculate_test_metrics(
        y_test, test_predictions, test_probabilities, labels
    )
    test_metrics.update(timing_metrics)
    test_metrics["Training_Time_s"] = float(training_time)
    test_metrics["Test_Loss"] = test_loss
    test_metrics["Validation_F1_macro"] = float(validation_macro_f1)
    test_metrics["Epochs_Completed"] = int(len(history.history.get("loss", [])))

    run_row = {"Model": MODEL_NAME, "Run": int(run_number), "Seed": int(seed)}
    run_row.update(test_metrics)
    run_rows.append(run_row)

    # Save all scalar metrics and readable macro/weighted subsets per seed.
    pd.DataFrame([run_row]).to_csv(seed_directory / "scalar_metrics.csv", index=False)

    macro_columns = [
        "Model", "Run", "Seed", "Precision_macro", "Recall_macro", "F1_macro",
        "ROC_AUC_macro_OvR", "FPR_macro"
    ]
    weighted_columns = [
        "Model", "Run", "Seed", "Precision_weighted", "Recall_weighted",
        "F1_weighted", "FPR_weighted"
    ]
    pd.DataFrame([run_row])[macro_columns].to_csv(
        seed_directory / "macro_metrics.csv", index=False
    )
    pd.DataFrame([run_row])[weighted_columns].to_csv(
        seed_directory / "weighted_average_metrics.csv", index=False
    )

    report = classification_report(
        y_test,
        test_predictions,
        labels=labels,
        target_names=label_encoder.classes_,
        output_dict=True,
        zero_division=0,
    )
    pd.DataFrame(report).transpose().to_csv(
        seed_directory / "classification_report.csv"
    )

    per_class_df = build_per_class_table(
        y_test, test_predictions, labels, per_class_fpr, class_matrices
    )
    per_class_df.insert(0, "Seed", int(seed))
    per_class_df.insert(0, "Run", int(run_number))
    per_class_df.insert(0, "Model", MODEL_NAME)
    per_class_df.to_csv(seed_directory / "per_class_metrics_and_fpr.csv", index=False)
    per_class_rows.extend(per_class_df.to_dict(orient="records"))

    pd.DataFrame([{
        "Model": MODEL_NAME,
        "Run": int(run_number),
        "Seed": int(seed),
        "FPR_macro": test_metrics["FPR_macro"],
        "FPR_micro_overall": test_metrics["FPR_micro_overall"],
        "FPR_weighted": test_metrics["FPR_weighted"],
    }]).to_csv(seed_directory / "false_positive_rate_summary.csv", index=False)

    save_confusion_matrix_outputs(
        y_test,
        test_predictions,
        seed_directory / "confusion_matrix",
    )

    pd.DataFrame(history.history).to_csv(
        seed_directory / "training_history.csv", index=False
    )

    prediction_df = pd.DataFrame({
        "True_Code": y_test,
        "True_Label": label_encoder.inverse_transform(y_test),
        "Predicted_Code": test_predictions,
        "Predicted_Label": label_encoder.inverse_transform(test_predictions),
    })
    for class_code, class_name in enumerate(label_encoder.classes_):
        prediction_df[f"Probability_{class_name}"] = test_probabilities[:, class_code]
    prediction_df.to_csv(
        seed_directory / "test_predictions_and_probabilities.csv", index=False
    )

    model_path = seed_directory / f"{MODEL_NAME.lower()}_seed_{seed}.keras"
    model.save(model_path)

    run_metadata = {
        "Model": MODEL_NAME,
        "Run": int(run_number),
        "Seed": int(seed),
        "Feature_Augmentation": False,
        "Optuna": False,
        "Training_Balancing": "SMOTE",
        "Split_Random_State": int(SEED),
        "SMOTE_Random_State": int(SEED),
        "Hyperparameters": BASELINE_HYPERPARAMETERS,
        "Training_Samples_After_SMOTE": int(len(X_train_input)),
        "Validation_Samples": int(len(X_val_input)),
        "Test_Samples": int(len(X_test_input)),
    }
    with (seed_directory / "run_metadata.json").open("w", encoding="utf-8") as f:
        json.dump(run_metadata, f, indent=2)

    representative_candidates.append({
        "Run": int(run_number),
        "Seed": int(seed),
        "F1_macro": float(test_metrics["F1_macro"]),
        "Predictions": test_predictions.copy(),
    })

    print(
        f"Completed seed {seed}: validation macro F1={validation_macro_f1:.6f}, "
        f"test macro F1={test_metrics['F1_macro']:.6f}"
    )

    del history, model
    gc.collect()
    tf.keras.backend.clear_session()

all_run_results = pd.DataFrame(run_rows)
all_per_class_results = pd.DataFrame(per_class_rows)

all_run_results.to_csv(
    OUTPUT_DIRECTORY / "dnn_5_seed_run_results.csv", index=False
)
all_per_class_results.to_csv(
    OUTPUT_DIRECTORY / "dnn_per_class_5_seed_run_results.csv", index=False
)

macro_metric_columns = [
    "Model", "Run", "Seed", "Precision_macro", "Recall_macro", "F1_macro",
    "ROC_AUC_macro_OvR", "FPR_macro"
]
weighted_metric_columns = [
    "Model", "Run", "Seed", "Precision_weighted", "Recall_weighted",
    "F1_weighted", "FPR_weighted"
]

macro_metrics_5_seed_results = all_run_results[macro_metric_columns].copy()
weighted_average_metrics_5_seed_results = all_run_results[weighted_metric_columns].copy()

macro_metrics_5_seed_results.to_csv(
    OUTPUT_DIRECTORY / "dnn_macro_metrics_5_seed_results.csv", index=False
)
weighted_average_metrics_5_seed_results.to_csv(
    OUTPUT_DIRECTORY / "dnn_weighted_average_metrics_5_seed_results.csv", index=False
)

display(all_run_results)
display(macro_metrics_5_seed_results)
display(weighted_average_metrics_5_seed_results)

================== DNN run 1/5 — seed 42 ==================
Epoch 1/100

2026-09-30 12:47:06.157770: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
2026-09-30 12:47:06.466958: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6086/6090 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7599 - loss: 0.5963

2026-09-30 12:47:28.046589: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.7914 - loss: 0.4923 - val_accuracy: 0.8339 - val_loss: 0.3654
Epoch 2/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8155 - loss: 0.4278 - val_accuracy: 0.8377 - val_loss: 0.3559
Epoch 3/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8218 - loss: 0.4143 - val_accuracy: 0.8432 - val_loss: 0.3502
Epoch 4/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8258 - loss: 0.4069 - val_accuracy: 0.8460 - val_loss: 0.3458
Epoch 5/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8281 - loss: 0.4019 - val_accuracy: 0.8453 - val_loss: 0.3443
Epoch 6/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.8307 - loss: 0.3982 - val_accuracy: 0.8475 - val_loss: 0.3410
Epoch 7/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8360 - loss: 0.3928 - val_accuracy: 0.8510 - val_loss: 0.3341
Epoch 8/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8443 - loss: 0.3854 - val_accuracy: 0.8834 - val_loss: 0.3108
Epoch 9/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8607 - loss: 0.3670 - val_accuracy: 0.9218 - val_loss: 0.2871
Epoch 10/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8799 - loss: 0.3431 - val_accuracy: 0.9433 - val_loss: 0.2362
Epoch 11/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8930 - loss: 0.3252 - val_accuracy: 0.9383 - val_loss: 0.2265
Epoch 12/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.9025 - loss: 0.3154 - val_accuracy: 0.9524 - val_loss: 0.2148
Epoch 13/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.9070 - loss: 0.3106 - val_accuracy: 0.9584 - val_loss: 0.2032
Epoch 14/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9086 - loss: 0.3099 - val_accuracy: 0.9593 - val_loss: 0.2030
Epoch 15/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9091 - loss: 0.3089 - val_accuracy: 0.9585 - val_loss: 0.2057
Epoch 16/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9115 - loss: 0.3031 - val_accuracy: 0.9586 - val_loss: 0.2031
Epoch 17/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.9133 - loss: 0.3006 - val_accuracy: 0.9599 - val_loss: 0.2023
Epoch 18/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9136 - loss: 0.3003 - val_accuracy: 0.9601 - val_loss: 0.1979
Epoch 19/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9149 - loss: 0.2980 - val_accuracy: 0.9597 - val_loss: 0.2035
Epoch 20/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9148 - loss: 0.2969 - val_accuracy: 0.9586 - val_loss: 0.2039
Epoch 21/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9162 - loss: 0.2960 - val_accuracy: 0.9623 - val_loss: 0.1972
Epoch 22/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9216 - loss: 0.2810 - val_accuracy: 0.9819 - val_loss: 0.1555
Epoch 23/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9259 - loss: 0.2687 - val_accuracy: 0.9822 - val_loss: 0.1550
Epoch 24/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9299 - loss: 0.2620 - val_accuracy: 0.9816 - val_loss: 0.1462
Epoch 25/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9316 - loss: 0.2610 - val_accuracy: 0.9816 - val_loss: 0.1542
Epoch 26/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9330 - loss: 0.2581 - val_accuracy: 0.9841 - val_loss: 0.1458
Epoch 27/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9333 - loss: 0.2566 - val_accuracy: 0.9791 - val_loss: 0.1505
Epoch 28/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9328 - loss: 0.2577 - val_accuracy: 0.9840 - val_loss: 0.1455
Epoch 29/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9326 - loss: 0.2569 - val_accuracy: 0.9815 - val_loss: 0.1476
Epoch 30/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9331 - loss: 0.2554 - val_accuracy: 0.9551 - val_loss: 0.1765
Epoch 31/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9275 - loss: 0.2651 - val_accuracy: 0.9838 - val_loss: 0.1398
Epoch 32/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9232 - loss: 0.2704 - val_accuracy: 0.9747 - val_loss: 0.1601
Epoch 33/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9179 - loss: 0.2772 - val_accuracy: 0.9648 - val_loss: 0.1695
Epoch 34/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9269 - loss: 0.2637 - val_accuracy: 0.9771 - val_loss: 0.1548
Epoch 35/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9324 - loss: 0.2572 - val_accuracy: 0.9828 - val_loss: 0.1472
Epoch 36/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.9331 - loss: 0.2563 - val_accuracy: 0.9832 - val_loss: 0.1398
Epoch 37/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.9331 - loss: 0.2558 - val_accuracy: 0.9839 - val_loss: 0.1441
Epoch 38/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.9330 - loss: 0.2561 - val_accuracy: 0.9842 - val_loss: 0.1416
Epoch 39/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.9337 - loss: 0.2556 - val_accuracy: 0.9835 - val_loss: 0.1403
Epoch 40/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 29s 5ms/step - accuracy: 0.9334 - loss: 0.2566 - val_accuracy: 0.9808 - val_loss: 0.1502
Epoch 41/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.9334 - loss: 0.2559 - val_accuracy: 0.9826 - val_loss: 0.1419
Epoch 41: early stopping
Restoring model weights from the end of the best epoch: 31.

2026-09-30 13:04:15.515596: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:04:27.638685: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:04:37.347417: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:04:48.545969: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:04:59.032204: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:05:09.826913: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:05:20.271466: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

Completed seed 42: validation macro F1=0.669746, test macro F1=0.658919

================== DNN run 2/5 — seed 43 ==================
Epoch 1/100

2026-09-30 13:05:37.872686: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6090/6090 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7628 - loss: 0.5873

2026-09-30 13:06:06.488465: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6090/6090 ━━━━━━━━━━━━━━━━━━━━ 34s 5ms/step - accuracy: 0.7921 - loss: 0.4899 - val_accuracy: 0.8333 - val_loss: 0.3664
Epoch 2/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 33s 5ms/step - accuracy: 0.8164 - loss: 0.4268 - val_accuracy: 0.8394 - val_loss: 0.3572
Epoch 3/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 31s 5ms/step - accuracy: 0.8228 - loss: 0.4135 - val_accuracy: 0.8453 - val_loss: 0.3504
Epoch 4/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.8269 - loss: 0.4066 - val_accuracy: 0.8459 - val_loss: 0.3450
Epoch 5/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 31s 5ms/step - accuracy: 0.8291 - loss: 0.4026 - val_accuracy: 0.8478 - val_loss: 0.3441
Epoch 6/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 36s 6ms/step - accuracy: 0.8306 - loss: 0.3993 - val_accuracy: 0.8481 - val_loss: 0.3440
Epoch 7/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 29s 5ms/step - accuracy: 0.8322 - loss: 0.3974 - val_accuracy: 0.8555 - val_loss: 0.3411
Epoch 8/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 29s 5ms/step - accuracy: 0.8335 - loss: 0.3949 - val_accuracy: 0.8564 - val_loss: 0.3393
Epoch 9/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8344 - loss: 0.3929 - val_accuracy: 0.8741 - val_loss: 0.3401
Epoch 10/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8364 - loss: 0.3915 - val_accuracy: 0.8720 - val_loss: 0.3373
Epoch 11/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8394 - loss: 0.3883 - val_accuracy: 0.8775 - val_loss: 0.3325
Epoch 12/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8453 - loss: 0.3835 - val_accuracy: 0.9016 - val_loss: 0.3230
Epoch 13/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8539 - loss: 0.3726 - val_accuracy: 0.9096 - val_loss: 0.2966
Epoch 14/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8770 - loss: 0.3457 - val_accuracy: 0.9334 - val_loss: 0.2513
Epoch 15/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8941 - loss: 0.3341 - val_accuracy: 0.9440 - val_loss: 0.2386
Epoch 16/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9011 - loss: 0.3251 - val_accuracy: 0.9483 - val_loss: 0.2249
Epoch 17/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9073 - loss: 0.3161 - val_accuracy: 0.9610 - val_loss: 0.2102
Epoch 18/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9132 - loss: 0.3072 - val_accuracy: 0.9565 - val_loss: 0.2055
Epoch 19/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9178 - loss: 0.3009 - val_accuracy: 0.9587 - val_loss: 0.1847
Epoch 20/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9220 - loss: 0.2961 - val_accuracy: 0.9736 - val_loss: 0.1875
Epoch 21/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9267 - loss: 0.2879 - val_accuracy: 0.9667 - val_loss: 0.1744
Epoch 22/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.9283 - loss: 0.2847 - val_accuracy: 0.9670 - val_loss: 0.1759
Epoch 23/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.9300 - loss: 0.2770 - val_accuracy: 0.9789 - val_loss: 0.1561
Epoch 24/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.9330 - loss: 0.2660 - val_accuracy: 0.9795 - val_loss: 0.1542
Epoch 25/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.9291 - loss: 0.2720 - val_accuracy: 0.9597 - val_loss: 0.1630
Epoch 26/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9287 - loss: 0.2675 - val_accuracy: 0.9763 - val_loss: 0.1641
Epoch 27/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9304 - loss: 0.2664 - val_accuracy: 0.9809 - val_loss: 0.1530
Epoch 28/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.9304 - loss: 0.2655 - val_accuracy: 0.9755 - val_loss: 0.1650
Epoch 29/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.9324 - loss: 0.2617 - val_accuracy: 0.9789 - val_loss: 0.1542
Epoch 30/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9348 - loss: 0.2586 - val_accuracy: 0.9799 - val_loss: 0.1658
Epoch 31/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9344 - loss: 0.2590 - val_accuracy: 0.9798 - val_loss: 0.1531
Epoch 32/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9320 - loss: 0.2617 - val_accuracy: 0.9799 - val_loss: 0.1445
Epoch 33/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.9338 - loss: 0.2587 - val_accuracy: 0.9765 - val_loss: 0.1566
Epoch 34/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9297 - loss: 0.2640 - val_accuracy: 0.9753 - val_loss: 0.1543
Epoch 35/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9309 - loss: 0.2629 - val_accuracy: 0.9773 - val_loss: 0.1516
Epoch 36/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9297 - loss: 0.2632 - val_accuracy: 0.9796 - val_loss: 0.1581
Epoch 37/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.9323 - loss: 0.2600 - val_accuracy: 0.9807 - val_loss: 0.1471
Epoch 38/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9326 - loss: 0.2592 - val_accuracy: 0.9814 - val_loss: 0.1448
Epoch 39/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9327 - loss: 0.2581 - val_accuracy: 0.9813 - val_loss: 0.1481
Epoch 40/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.9335 - loss: 0.2568 - val_accuracy: 0.9808 - val_loss: 0.1537
Epoch 41/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.9346 - loss: 0.2547 - val_accuracy: 0.9825 - val_loss: 0.1450
Epoch 42/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.9342 - loss: 0.2540 - val_accuracy: 0.9770 - val_loss: 0.1521
Epoch 42: early stopping
Restoring model weights from the end of the best epoch: 32.

2026-09-30 13:20:35.466564: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:20:41.387898: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:20:46.628049: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:20:51.814190: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:21:00.473815: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}

Completed seed 43: validation macro F1=0.654035, test macro F1=0.651034

================== DNN run 3/5 — seed 44 ==================
Epoch 1/100

2026-09-30 13:21:17.364567: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6080/6090 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7638 - loss: 0.6017

2026-09-30 13:21:36.264302: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.7910 - loss: 0.4979 - val_accuracy: 0.8350 - val_loss: 0.3623
Epoch 2/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8155 - loss: 0.4292 - val_accuracy: 0.8390 - val_loss: 0.3535
Epoch 3/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8215 - loss: 0.4148 - val_accuracy: 0.8440 - val_loss: 0.3481
Epoch 4/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8253 - loss: 0.4077 - val_accuracy: 0.8454 - val_loss: 0.3460
Epoch 5/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8270 - loss: 0.4037 - val_accuracy: 0.8424 - val_loss: 0.3470
Epoch 6/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8289 - loss: 0.4008 - val_accuracy: 0.8487 - val_loss: 0.3437
Epoch 7/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8298 - loss: 0.3989 - val_accuracy: 0.8484 - val_loss: 0.3423
Epoch 8/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8309 - loss: 0.3976 - val_accuracy: 0.8480 - val_loss: 0.3417
Epoch 9/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8314 - loss: 0.3956 - val_accuracy: 0.8536 - val_loss: 0.3392
Epoch 10/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8330 - loss: 0.3935 - val_accuracy: 0.8550 - val_loss: 0.3371
Epoch 11/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8350 - loss: 0.3922 - val_accuracy: 0.8566 - val_loss: 0.3339
Epoch 12/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8388 - loss: 0.3891 - val_accuracy: 0.8607 - val_loss: 0.3282
Epoch 13/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8416 - loss: 0.3865 - val_accuracy: 0.8602 - val_loss: 0.3250
Epoch 14/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8441 - loss: 0.3841 - val_accuracy: 0.8643 - val_loss: 0.3260
Epoch 15/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8468 - loss: 0.3815 - val_accuracy: 0.8644 - val_loss: 0.3196
Epoch 16/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8488 - loss: 0.3794 - val_accuracy: 0.8680 - val_loss: 0.3187
Epoch 17/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8508 - loss: 0.3758 - val_accuracy: 0.8749 - val_loss: 0.3135
Epoch 18/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8544 - loss: 0.3709 - val_accuracy: 0.8906 - val_loss: 0.2955
Epoch 19/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8568 - loss: 0.3667 - val_accuracy: 0.8836 - val_loss: 0.2945
Epoch 20/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8618 - loss: 0.3607 - val_accuracy: 0.8972 - val_loss: 0.2755
Epoch 21/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8713 - loss: 0.3504 - val_accuracy: 0.9057 - val_loss: 0.2628
Epoch 22/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8760 - loss: 0.3392 - val_accuracy: 0.9165 - val_loss: 0.2330
Epoch 23/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8796 - loss: 0.3310 - val_accuracy: 0.9189 - val_loss: 0.2264
Epoch 24/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8797 - loss: 0.3309 - val_accuracy: 0.9125 - val_loss: 0.2295
Epoch 25/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.8798 - loss: 0.3300 - val_accuracy: 0.9354 - val_loss: 0.2188
Epoch 26/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.8807 - loss: 0.3286 - val_accuracy: 0.9155 - val_loss: 0.2313
Epoch 27/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8807 - loss: 0.3296 - val_accuracy: 0.9373 - val_loss: 0.2171
Epoch 28/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8818 - loss: 0.3279 - val_accuracy: 0.9247 - val_loss: 0.2163
Epoch 29/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8815 - loss: 0.3280 - val_accuracy: 0.9206 - val_loss: 0.2213
Epoch 30/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8823 - loss: 0.3273 - val_accuracy: 0.9359 - val_loss: 0.2173
Epoch 31/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8832 - loss: 0.3265 - val_accuracy: 0.9132 - val_loss: 0.2277
Epoch 32/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8845 - loss: 0.3234 - val_accuracy: 0.9446 - val_loss: 0.2102
Epoch 33/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8864 - loss: 0.3215 - val_accuracy: 0.9274 - val_loss: 0.2179
Epoch 34/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8873 - loss: 0.3204 - val_accuracy: 0.9428 - val_loss: 0.2106
Epoch 35/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8874 - loss: 0.3187 - val_accuracy: 0.9400 - val_loss: 0.2134
Epoch 36/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8875 - loss: 0.3197 - val_accuracy: 0.9193 - val_loss: 0.2160
Epoch 37/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8891 - loss: 0.3164 - val_accuracy: 0.9187 - val_loss: 0.2167
Epoch 38/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8893 - loss: 0.3178 - val_accuracy: 0.9473 - val_loss: 0.2025
Epoch 39/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8937 - loss: 0.3125 - val_accuracy: 0.9445 - val_loss: 0.2055
Epoch 40/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9049 - loss: 0.3024 - val_accuracy: 0.9569 - val_loss: 0.1875
Epoch 41/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9145 - loss: 0.2925 - val_accuracy: 0.9432 - val_loss: 0.2041
Epoch 42/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9257 - loss: 0.2747 - val_accuracy: 0.9693 - val_loss: 0.1679
Epoch 43/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.9275 - loss: 0.2696 - val_accuracy: 0.9765 - val_loss: 0.1586
Epoch 44/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9284 - loss: 0.2671 - val_accuracy: 0.9702 - val_loss: 0.1588
Epoch 45/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9278 - loss: 0.2674 - val_accuracy: 0.9755 - val_loss: 0.1579
Epoch 46/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 33s 5ms/step - accuracy: 0.9278 - loss: 0.2665 - val_accuracy: 0.9693 - val_loss: 0.1671
Epoch 47/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.9239 - loss: 0.2725 - val_accuracy: 0.9581 - val_loss: 0.1784
Epoch 48/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.9106 - loss: 0.2883 - val_accuracy: 0.9672 - val_loss: 0.1696
Epoch 49/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.9263 - loss: 0.2671 - val_accuracy: 0.9677 - val_loss: 0.1693
Epoch 50/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 33s 5ms/step - accuracy: 0.9271 - loss: 0.2668 - val_accuracy: 0.9747 - val_loss: 0.1611
Epoch 51/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 33s 5ms/step - accuracy: 0.9290 - loss: 0.2642 - val_accuracy: 0.9734 - val_loss: 0.1561
Epoch 52/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 37s 6ms/step - accuracy: 0.9267 - loss: 0.2665 - val_accuracy: 0.9749 - val_loss: 0.1657
Epoch 53/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 37s 6ms/step - accuracy: 0.9131 - loss: 0.2843 - val_accuracy: 0.9426 - val_loss: 0.1902
Epoch 54/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 37s 6ms/step - accuracy: 0.9124 - loss: 0.2844 - val_accuracy: 0.9654 - val_loss: 0.1745
Epoch 55/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 36s 6ms/step - accuracy: 0.9130 - loss: 0.2839 - val_accuracy: 0.9637 - val_loss: 0.1750
Epoch 56/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 42s 7ms/step - accuracy: 0.9120 - loss: 0.2849 - val_accuracy: 0.9663 - val_loss: 0.1756
Epoch 57/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 40s 7ms/step - accuracy: 0.9120 - loss: 0.2860 - val_accuracy: 0.9697 - val_loss: 0.1682
Epoch 58/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 31s 5ms/step - accuracy: 0.9126 - loss: 0.2840 - val_accuracy: 0.9708 - val_loss: 0.1685
Epoch 59/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 31s 5ms/step - accuracy: 0.9113 - loss: 0.2864 - val_accuracy: 0.9665 - val_loss: 0.1698
Epoch 60/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 31s 5ms/step - accuracy: 0.9124 - loss: 0.2836 - val_accuracy: 0.9718 - val_loss: 0.1723
Epoch 61/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.9131 - loss: 0.2829 - val_accuracy: 0.9736 - val_loss: 0.1685
Epoch 61: early stopping
Restoring model weights from the end of the best epoch: 51.

2026-09-30 13:47:38.730853: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:47:49.989717: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:48:01.144517: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:48:10.787704: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:48:19.744160: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:48:28.609531: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 13:48:38.527275: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

Completed seed 44: validation macro F1=0.668871, test macro F1=0.659294

================== DNN run 4/5 — seed 45 ==================
Epoch 1/100

2026-09-30 13:48:53.498817: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6082/6090 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7658 - loss: 0.5791

2026-09-30 13:49:17.863379: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6090/6090 ━━━━━━━━━━━━━━━━━━━━ 30s 5ms/step - accuracy: 0.7928 - loss: 0.4873 - val_accuracy: 0.8331 - val_loss: 0.3644
Epoch 2/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.8158 - loss: 0.4287 - val_accuracy: 0.8380 - val_loss: 0.3552
Epoch 3/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8214 - loss: 0.4173 - val_accuracy: 0.8391 - val_loss: 0.3521
Epoch 4/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8246 - loss: 0.4100 - val_accuracy: 0.8425 - val_loss: 0.3479
Epoch 5/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8260 - loss: 0.4062 - val_accuracy: 0.8459 - val_loss: 0.3438
Epoch 6/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - accuracy: 0.8286 - loss: 0.4022 - val_accuracy: 0.8448 - val_loss: 0.3432
Epoch 7/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8304 - loss: 0.3993 - val_accuracy: 0.8465 - val_loss: 0.3426
Epoch 8/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 27s 4ms/step - accuracy: 0.8317 - loss: 0.3977 - val_accuracy: 0.8476 - val_loss: 0.3399
Epoch 9/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8321 - loss: 0.3960 - val_accuracy: 0.8480 - val_loss: 0.3396
Epoch 10/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8327 - loss: 0.3943 - val_accuracy: 0.8477 - val_loss: 0.3390
Epoch 11/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8335 - loss: 0.3941 - val_accuracy: 0.8476 - val_loss: 0.3393
Epoch 12/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8341 - loss: 0.3924 - val_accuracy: 0.8469 - val_loss: 0.3390
Epoch 13/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8349 - loss: 0.3912 - val_accuracy: 0.8510 - val_loss: 0.3359
Epoch 14/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8356 - loss: 0.3908 - val_accuracy: 0.8521 - val_loss: 0.3367
Epoch 15/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8364 - loss: 0.3897 - val_accuracy: 0.8572 - val_loss: 0.3355
Epoch 16/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8369 - loss: 0.3886 - val_accuracy: 0.8507 - val_loss: 0.3347
Epoch 17/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8365 - loss: 0.3892 - val_accuracy: 0.8503 - val_loss: 0.3345
Epoch 18/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8374 - loss: 0.3874 - val_accuracy: 0.8500 - val_loss: 0.3342
Epoch 19/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8383 - loss: 0.3863 - val_accuracy: 0.8558 - val_loss: 0.3322
Epoch 20/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.8390 - loss: 0.3863 - val_accuracy: 0.8558 - val_loss: 0.3308
Epoch 21/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8403 - loss: 0.3852 - val_accuracy: 0.8533 - val_loss: 0.3284
Epoch 22/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8426 - loss: 0.3837 - val_accuracy: 0.8604 - val_loss: 0.3249
Epoch 23/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8474 - loss: 0.3785 - val_accuracy: 0.8591 - val_loss: 0.3207
Epoch 24/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8532 - loss: 0.3705 - val_accuracy: 0.8721 - val_loss: 0.3090
Epoch 25/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8606 - loss: 0.3623 - val_accuracy: 0.8879 - val_loss: 0.2967
Epoch 26/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8672 - loss: 0.3527 - val_accuracy: 0.9205 - val_loss: 0.2697
Epoch 27/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8780 - loss: 0.3379 - val_accuracy: 0.9406 - val_loss: 0.2281
Epoch 28/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8837 - loss: 0.3268 - val_accuracy: 0.9413 - val_loss: 0.2248
Epoch 29/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8858 - loss: 0.3229 - val_accuracy: 0.9444 - val_loss: 0.2164
Epoch 30/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8867 - loss: 0.3197 - val_accuracy: 0.9481 - val_loss: 0.2076
Epoch 31/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8868 - loss: 0.3183 - val_accuracy: 0.9471 - val_loss: 0.2042
Epoch 32/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8866 - loss: 0.3187 - val_accuracy: 0.9417 - val_loss: 0.2224
Epoch 33/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.8869 - loss: 0.3169 - val_accuracy: 0.9438 - val_loss: 0.2197
Epoch 34/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8872 - loss: 0.3155 - val_accuracy: 0.9494 - val_loss: 0.2065
Epoch 35/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - accuracy: 0.8869 - loss: 0.3172 - val_accuracy: 0.9519 - val_loss: 0.1979
Epoch 36/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8869 - loss: 0.3153 - val_accuracy: 0.9458 - val_loss: 0.2103
Epoch 37/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8875 - loss: 0.3151 - val_accuracy: 0.9510 - val_loss: 0.1970
Epoch 38/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8885 - loss: 0.3140 - val_accuracy: 0.9511 - val_loss: 0.2025
Epoch 39/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8885 - loss: 0.3130 - val_accuracy: 0.9483 - val_loss: 0.1999
Epoch 40/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8883 - loss: 0.3134 - val_accuracy: 0.9499 - val_loss: 0.1965
Epoch 41/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8893 - loss: 0.3109 - val_accuracy: 0.9561 - val_loss: 0.1984
Epoch 42/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8886 - loss: 0.3118 - val_accuracy: 0.9553 - val_loss: 0.1922
Epoch 43/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8893 - loss: 0.3111 - val_accuracy: 0.9555 - val_loss: 0.1910
Epoch 44/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8888 - loss: 0.3099 - val_accuracy: 0.9541 - val_loss: 0.1974
Epoch 45/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8891 - loss: 0.3080 - val_accuracy: 0.9578 - val_loss: 0.1868
Epoch 46/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.8892 - loss: 0.3071 - val_accuracy: 0.9560 - val_loss: 0.1916
Epoch 47/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.8900 - loss: 0.3061 - val_accuracy: 0.9503 - val_loss: 0.1894
Epoch 48/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8894 - loss: 0.3076 - val_accuracy: 0.9502 - val_loss: 0.2020
Epoch 49/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8885 - loss: 0.3075 - val_accuracy: 0.9506 - val_loss: 0.1994
Epoch 50/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.8891 - loss: 0.3073 - val_accuracy: 0.9537 - val_loss: 0.1855
Epoch 51/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - accuracy: 0.8897 - loss: 0.3066 - val_accuracy: 0.9559 - val_loss: 0.1836
Epoch 52/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8889 - loss: 0.3073 - val_accuracy: 0.9531 - val_loss: 0.1894
Epoch 53/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8903 - loss: 0.3060 - val_accuracy: 0.9520 - val_loss: 0.1952
Epoch 54/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.8890 - loss: 0.3066 - val_accuracy: 0.9522 - val_loss: 0.1865
Epoch 55/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.8888 - loss: 0.3087 - val_accuracy: 0.9472 - val_loss: 0.2003
Epoch 56/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.8903 - loss: 0.3068 - val_accuracy: 0.9510 - val_loss: 0.1932
Epoch 57/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8898 - loss: 0.3062 - val_accuracy: 0.9557 - val_loss: 0.1917
Epoch 58/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.8894 - loss: 0.3081 - val_accuracy: 0.9513 - val_loss: 0.1932
Epoch 59/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.8891 - loss: 0.3074 - val_accuracy: 0.9525 - val_loss: 0.1897
Epoch 60/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8907 - loss: 0.3059 - val_accuracy: 0.9496 - val_loss: 0.1941
Epoch 61/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8908 - loss: 0.3054 - val_accuracy: 0.9532 - val_loss: 0.1882
Epoch 61: early stopping
Restoring model weights from the end of the best epoch: 51.

2026-09-30 14:12:08.568531: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:12:16.326336: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:12:23.555727: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:12:30.962011: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:12:38.635869: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:12:46.385631: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:12:53.776419: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

Completed seed 45: validation macro F1=0.654988, test macro F1=0.649617

================== DNN run 5/5 — seed 46 ==================
Epoch 1/100

2026-09-30 14:13:05.477657: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6082/6090 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7613 - loss: 0.5957

2026-09-30 14:13:24.726377: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.7912 - loss: 0.4935 - val_accuracy: 0.8296 - val_loss: 0.3690
Epoch 2/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8150 - loss: 0.4304 - val_accuracy: 0.8364 - val_loss: 0.3595
Epoch 3/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8210 - loss: 0.4175 - val_accuracy: 0.8392 - val_loss: 0.3542
Epoch 4/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.8245 - loss: 0.4099 - val_accuracy: 0.8434 - val_loss: 0.3473
Epoch 5/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8269 - loss: 0.4050 - val_accuracy: 0.8448 - val_loss: 0.3457
Epoch 6/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8285 - loss: 0.4019 - val_accuracy: 0.8455 - val_loss: 0.3434
Epoch 7/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8301 - loss: 0.3994 - val_accuracy: 0.8492 - val_loss: 0.3434
Epoch 8/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8315 - loss: 0.3970 - val_accuracy: 0.8461 - val_loss: 0.3440
Epoch 9/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8330 - loss: 0.3959 - val_accuracy: 0.8490 - val_loss: 0.3382
Epoch 10/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8357 - loss: 0.3928 - val_accuracy: 0.8513 - val_loss: 0.3352
Epoch 11/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8381 - loss: 0.3907 - val_accuracy: 0.8539 - val_loss: 0.3327
Epoch 12/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8428 - loss: 0.3881 - val_accuracy: 0.8746 - val_loss: 0.3265
Epoch 13/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8460 - loss: 0.3851 - val_accuracy: 0.8767 - val_loss: 0.3224
Epoch 14/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8492 - loss: 0.3829 - val_accuracy: 0.8787 - val_loss: 0.3204
Epoch 15/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8514 - loss: 0.3808 - val_accuracy: 0.8819 - val_loss: 0.3132
Epoch 16/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8545 - loss: 0.3777 - val_accuracy: 0.8857 - val_loss: 0.3081
Epoch 17/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.8596 - loss: 0.3699 - val_accuracy: 0.9128 - val_loss: 0.2879
Epoch 18/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8700 - loss: 0.3569 - val_accuracy: 0.9286 - val_loss: 0.2618
Epoch 19/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8894 - loss: 0.3324 - val_accuracy: 0.9434 - val_loss: 0.2259
Epoch 20/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9038 - loss: 0.3167 - val_accuracy: 0.9539 - val_loss: 0.2120
Epoch 21/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.9087 - loss: 0.3117 - val_accuracy: 0.9517 - val_loss: 0.2135
Epoch 22/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.9126 - loss: 0.3063 - val_accuracy: 0.9596 - val_loss: 0.2040
Epoch 23/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9172 - loss: 0.2985 - val_accuracy: 0.9612 - val_loss: 0.1980
Epoch 24/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9186 - loss: 0.2959 - val_accuracy: 0.9790 - val_loss: 0.1645
Epoch 25/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9289 - loss: 0.2681 - val_accuracy: 0.9809 - val_loss: 0.1581
Epoch 26/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9299 - loss: 0.2661 - val_accuracy: 0.9793 - val_loss: 0.1597
Epoch 27/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9290 - loss: 0.2683 - val_accuracy: 0.9767 - val_loss: 0.1678
Epoch 28/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9307 - loss: 0.2652 - val_accuracy: 0.9784 - val_loss: 0.1540
Epoch 29/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9335 - loss: 0.2608 - val_accuracy: 0.9807 - val_loss: 0.1502
Epoch 30/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9343 - loss: 0.2591 - val_accuracy: 0.9783 - val_loss: 0.1539
Epoch 31/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9339 - loss: 0.2588 - val_accuracy: 0.9835 - val_loss: 0.1435
Epoch 32/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9341 - loss: 0.2582 - val_accuracy: 0.9807 - val_loss: 0.1464
Epoch 33/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9342 - loss: 0.2579 - val_accuracy: 0.9810 - val_loss: 0.1483
Epoch 34/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9334 - loss: 0.2595 - val_accuracy: 0.9782 - val_loss: 0.1520
Epoch 35/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9345 - loss: 0.2575 - val_accuracy: 0.9784 - val_loss: 0.1511
Epoch 36/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - accuracy: 0.9329 - loss: 0.2590 - val_accuracy: 0.9829 - val_loss: 0.1397
Epoch 37/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9361 - loss: 0.2533 - val_accuracy: 0.9821 - val_loss: 0.1435
Epoch 38/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9342 - loss: 0.2561 - val_accuracy: 0.9758 - val_loss: 0.1570
Epoch 39/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9215 - loss: 0.2712 - val_accuracy: 0.9741 - val_loss: 0.1652
Epoch 40/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9347 - loss: 0.2542 - val_accuracy: 0.9826 - val_loss: 0.1458
Epoch 41/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9376 - loss: 0.2510 - val_accuracy: 0.9839 - val_loss: 0.1390
Epoch 42/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9373 - loss: 0.2503 - val_accuracy: 0.9819 - val_loss: 0.1452
Epoch 43/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9373 - loss: 0.2505 - val_accuracy: 0.9834 - val_loss: 0.1373
Epoch 44/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9374 - loss: 0.2495 - val_accuracy: 0.9830 - val_loss: 0.1405
Epoch 45/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.9386 - loss: 0.2487 - val_accuracy: 0.9836 - val_loss: 0.1405
Epoch 46/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9376 - loss: 0.2497 - val_accuracy: 0.9842 - val_loss: 0.1420
Epoch 47/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9388 - loss: 0.2480 - val_accuracy: 0.9849 - val_loss: 0.1314
Epoch 48/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9415 - loss: 0.2408 - val_accuracy: 0.9835 - val_loss: 0.1333
Epoch 49/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9428 - loss: 0.2386 - val_accuracy: 0.9806 - val_loss: 0.1500
Epoch 50/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9422 - loss: 0.2404 - val_accuracy: 0.9836 - val_loss: 0.1363
Epoch 51/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9409 - loss: 0.2420 - val_accuracy: 0.9832 - val_loss: 0.1367
Epoch 52/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9422 - loss: 0.2399 - val_accuracy: 0.9831 - val_loss: 0.1340
Epoch 53/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9430 - loss: 0.2392 - val_accuracy: 0.9824 - val_loss: 0.1406
Epoch 54/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9415 - loss: 0.2419 - val_accuracy: 0.9838 - val_loss: 0.1308
Epoch 55/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9427 - loss: 0.2388 - val_accuracy: 0.9832 - val_loss: 0.1356
Epoch 56/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9431 - loss: 0.2384 - val_accuracy: 0.9850 - val_loss: 0.1337
Epoch 57/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9431 - loss: 0.2390 - val_accuracy: 0.9835 - val_loss: 0.1321
Epoch 58/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9425 - loss: 0.2396 - val_accuracy: 0.9841 - val_loss: 0.1328
Epoch 59/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9434 - loss: 0.2383 - val_accuracy: 0.9829 - val_loss: 0.1401
Epoch 60/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9434 - loss: 0.2390 - val_accuracy: 0.9846 - val_loss: 0.1290
Epoch 61/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9416 - loss: 0.2417 - val_accuracy: 0.9833 - val_loss: 0.1370
Epoch 62/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9390 - loss: 0.2482 - val_accuracy: 0.9838 - val_loss: 0.1454
Epoch 63/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9402 - loss: 0.2434 - val_accuracy: 0.9842 - val_loss: 0.1301
Epoch 64/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9427 - loss: 0.2384 - val_accuracy: 0.9827 - val_loss: 0.1400
Epoch 65/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.9433 - loss: 0.2371 - val_accuracy: 0.9860 - val_loss: 0.1294
Epoch 66/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9441 - loss: 0.2361 - val_accuracy: 0.9843 - val_loss: 0.1340
Epoch 67/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.9442 - loss: 0.2349 - val_accuracy: 0.9852 - val_loss: 0.1307
Epoch 68/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.9432 - loss: 0.2374 - val_accuracy: 0.9850 - val_loss: 0.1370
Epoch 69/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9402 - loss: 0.2458 - val_accuracy: 0.9850 - val_loss: 0.1352
Epoch 70/100
6090/6090 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.9403 - loss: 0.2426 - val_accuracy: 0.9841 - val_loss: 0.1342
Epoch 70: early stopping
Restoring model weights from the end of the best epoch: 60.

2026-09-30 14:39:32.616269: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:39:41.428363: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:39:49.197457: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:39:57.027370: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:40:05.068703: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:40:12.995634: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_14}}
2026-09-30 14:40:21.352307: E tensorflow/core/framework/node_def_util.cc:680] NodeDef mentions attribute use_unbounded_threadpool which is not in the op definition: Op<name=MapDataset; signature=input_dataset:variant, other_arguments: -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=preserve_cardinality:bool,default=false; attr=force_synchronous:bool,default=false; attr=metadata:string,default=""> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_15}}

Completed seed 46: validation macro F1=0.668465, test macro F1=0.660213

,Model,Run,Seed,Accuracy,Precision_macro,Recall_macro,F1_macro,Precision_weighted,Recall_weighted,F1_weighted,...,FPR_macro,FPR_micro_overall,FPR_weighted,Inference_Time_s,Latency_ms_per_sample,Throughput_samples_per_s,Training_Time_s,Test_Loss,Validation_F1_macro,Epochs_Completed
0,DNN,1,42,0.982832,0.678980,0.732992,0.658919,0.987580,0.982832,0.984771,...,0.003039,0.002453,0.007148,10.521855,0.088983,11238.132317,1029.186358,0.141162,0.669746,41
1,DNN,2,43,0.979847,0.676263,0.741593,0.651034,0.986418,0.979847,0.982562,...,0.003734,0.002879,0.009717,4.784262,0.040460,24715.617554,897.694349,0.144271,0.654035,42
2,DNN,3,44,0.972422,0.674390,0.721418,0.659294,0.975813,0.972422,0.973609,...,0.007666,0.003940,0.033750,9.706306,0.082086,12182.389004,1581.434404,0.157470,0.668871,61
3,DNN,4,45,0.956066,0.673813,0.720819,0.649617,0.961021,0.956066,0.956672,...,0.015428,0.006276,0.079489,7.489982,0.063342,15787.220458,1395.156424,0.184427,0.654988,61
4,DNN,5,46,0.983543,0.665437,0.726484,0.660213,0.987264,0.983543,0.985183,...,0.002726,0.002351,0.005347,7.982800,0.067510,14812.597302,1587.198228,0.130542,0.668465,70

,Model,Run,Seed,Precision_macro,Recall_macro,F1_macro,ROC_AUC_macro_OvR,FPR_macro
0,DNN,1,42,0.678980,0.732992,0.658919,0.992001,0.003039
1,DNN,2,43,0.676263,0.741593,0.651034,0.993538,0.003734
2,DNN,3,44,0.674390,0.721418,0.659294,0.991650,0.007666
3,DNN,4,45,0.673813,0.720819,0.649617,0.990792,0.015428
4,DNN,5,46,0.665437,0.726484,0.660213,0.989031,0.002726

,Model,Run,Seed,Precision_weighted,Recall_weighted,F1_weighted,FPR_weighted
0,DNN,1,42,0.987580,0.982832,0.984771,0.007148
1,DNN,2,43,0.986418,0.979847,0.982562,0.009717
2,DNN,3,44,0.975813,0.972422,0.973609,0.033750
3,DNN,4,45,0.961021,0.956066,0.956672,0.079489
4,DNN,5,46,0.987264,0.983543,0.985183,0.005347

## 7. Five-run mean ± sample SD and representative DNN run

In [11]:
# ============================================================
# Five-run mean ± sample SD summaries
# ============================================================
identifier_columns = {"Model", "Run", "Seed"}
metric_columns = [c for c in all_run_results.columns if c not in identifier_columns]
summary_records = []

for metric_name in metric_columns:
    values = pd.to_numeric(all_run_results[metric_name], errors="coerce")
    metric_mean = float(values.mean())
    metric_sd = float(values.std(ddof=1))
    summary_records.append({
        "Model": "DNN",
        "Metric": metric_name,
        "Mean": metric_mean,
        "SD": metric_sd,
        "N": int(values.notna().sum()),
        "Mean ± SD": format_mean_sd(metric_mean, metric_sd),
    })

five_run_summary_long = pd.DataFrame(summary_records)
five_run_summary_table = five_run_summary_long.pivot(
    index="Model", columns="Metric", values="Mean ± SD"
).reindex(["DNN"])

five_run_summary_long.to_csv(
    OUTPUT_DIRECTORY / "five_run_mean_sd_long.csv", index=False
)
five_run_summary_table.to_csv(
    OUTPUT_DIRECTORY / "five_run_mean_sd_report_table.csv"
)

macro_summary_names = [
    "Precision_macro", "Recall_macro", "F1_macro", "ROC_AUC_macro_OvR", "FPR_macro"
]
weighted_summary_names = [
    "Precision_weighted", "Recall_weighted", "F1_weighted", "FPR_weighted"
]

macro_metrics_mean_sd = five_run_summary_long[
    five_run_summary_long["Metric"].isin(macro_summary_names)
].reset_index(drop=True)
weighted_average_metrics_mean_sd = five_run_summary_long[
    five_run_summary_long["Metric"].isin(weighted_summary_names)
].reset_index(drop=True)

macro_metrics_mean_sd.to_csv(
    OUTPUT_DIRECTORY / "macro_metrics_5_seed_mean_sd.csv", index=False
)
weighted_average_metrics_mean_sd.to_csv(
    OUTPUT_DIRECTORY / "weighted_average_metrics_5_seed_mean_sd.csv", index=False
)

# Per-class five-run mean ± sample SD.
per_class_summary_records = []
for class_name, class_rows in all_per_class_results.groupby("Class", sort=False):
    record = {
        "Model": "DNN",
        "Class": class_name,
        "Support": int(class_rows["Support"].iloc[0]),
        "N": int(len(class_rows)),
    }
    for metric_name in ["Precision", "Recall", "F1", "FPR"]:
        metric_mean = float(class_rows[metric_name].mean())
        metric_sd = float(class_rows[metric_name].std(ddof=1))
        record[f"{metric_name}_Mean"] = metric_mean
        record[f"{metric_name}_SD"] = metric_sd
        record[f"{metric_name}_Mean ± SD"] = format_mean_sd(metric_mean, metric_sd)
    per_class_summary_records.append(record)

per_class_mean_sd = pd.DataFrame(per_class_summary_records)
per_class_mean_sd.to_csv(
    OUTPUT_DIRECTORY / "per_class_five_run_mean_sd.csv", index=False
)

# Representative run: test macro F1 closest to the five-run mean.
mean_macro_f1 = float(all_run_results["F1_macro"].mean())
representative = min(
    representative_candidates,
    key=lambda item: abs(item["F1_macro"] - mean_macro_f1),
)
representative_runs = pd.DataFrame([{
    "Model": "DNN",
    "Representative_Run": representative["Run"],
    "Representative_Seed": representative["Seed"],
    "Representative_F1_macro": representative["F1_macro"],
    "Five_Run_Mean_F1_macro": mean_macro_f1,
}])
representative_runs.to_csv(
    OUTPUT_DIRECTORY / "representative_runs.csv", index=False
)

save_confusion_matrix_outputs(
    y_test,
    representative["Predictions"],
    OUTPUT_DIRECTORY / "dnn_representative_confusion_matrix",
)
representative_report = classification_report(
    y_test,
    representative["Predictions"],
    labels=np.arange(number_of_classes),
    target_names=label_encoder.classes_,
    output_dict=True,
    zero_division=0,
)
pd.DataFrame(representative_report).transpose().to_csv(
    OUTPUT_DIRECTORY / "dnn_representative_classification_report.csv"
)

# Compact macro and weighted journal tables in the preferred metric order.
def build_compact_journal_table(average_kind):
    summary_index = five_run_summary_long.set_index("Metric")
    if average_kind == "macro":
        mapping = [
            ("Accuracy", "Accuracy (%)", True, 2),
            ("Recall_macro", "Recall (macro %)", True, 2),
            ("Precision_macro", "Precision (macro %)", True, 2),
            ("F1_macro", "F1-score (macro %)", True, 2),
            ("FPR_macro", "FPR (macro %)", True, 4),
        ]
    else:
        mapping = [
            ("Accuracy", "Accuracy (%)", True, 2),
            ("Recall_weighted", "Recall (weighted %)", True, 2),
            ("Precision_weighted", "Precision (weighted %)", True, 2),
            ("F1_weighted", "F1-score (weighted %)", True, 2),
            ("FPR_weighted", "FPR (weighted %)", True, 4),
        ]

    row = {"Model": "DNN"}
    for metric, display_name, pct, decimals in mapping:
        row[display_name] = format_mean_sd(
            float(summary_index.loc[metric, "Mean"]),
            float(summary_index.loc[metric, "SD"]),
            decimals=decimals,
            percentage=pct,
        )
    return pd.DataFrame([row])

macro_journal_table = build_compact_journal_table("macro")
weighted_journal_table = build_compact_journal_table("weighted")
macro_journal_table.to_csv(
    OUTPUT_DIRECTORY / "journal_macro_mean_sd_table.csv", index=False
)
weighted_journal_table.to_csv(
    OUTPUT_DIRECTORY / "journal_weighted_mean_sd_table.csv", index=False
)

print("Five-run mean ± sample SD (n=5):")
display(five_run_summary_table)
print("Macro mean ± SD:")
display(macro_metrics_mean_sd)
print("Weighted mean ± SD:")
display(weighted_average_metrics_mean_sd)
print("Representative run:")
display(representative_runs)
print("All outputs saved to:", OUTPUT_DIRECTORY.resolve())

Five-run mean ± sample SD (n=5):

Metric,Accuracy,Epochs_Completed,F1_macro,F1_weighted,FPR_macro,FPR_micro_overall,FPR_weighted,Inference_Time_s,Latency_ms_per_sample,MCC,Precision_macro,Precision_weighted,ROC_AUC_macro_OvR,Recall_macro,Recall_weighted,Test_Loss,Throughput_samples_per_s,Training_Time_s,Validation_F1_macro
Model,,,,,,,,,,,,,,,,,,,
DNN,0.974942 ± 0.011434,55.000000 ± 12.864680,0.655815 ± 0.005058,0.976559 ± 0.012063,0.006519 ± 0.005360,0.003580 ± 0.001633,0.027090 ± 0.031473,8.097041 ± 2.226294,0.068476 ± 0.018828,0.942261 ± 0.026749,0.673776 ± 0.005079,0.979619 ± 0.011494,0.991402 ± 0.001656,0.728661 ± 0.008728,0.974942 ± 0.011434,0.151574 ± 0.020725,15747.191327 ± 5346.661717,1298.133952 ± 318.557430,0.663221 ± 0.007971

Macro mean ± SD:

  Model             Metric      Mean        SD  N            Mean ± SD
0   DNN    Precision_macro  0.673776  0.005079  5  0.673776 ± 0.005079
1   DNN       Recall_macro  0.728661  0.008728  5  0.728661 ± 0.008728
2   DNN           F1_macro  0.655815  0.005058  5  0.655815 ± 0.005058
3   DNN  ROC_AUC_macro_OvR  0.991402  0.001656  5  0.991402 ± 0.001656
4   DNN          FPR_macro  0.006519  0.005360  5  0.006519 ± 0.005360

Weighted mean ± SD:

  Model              Metric      Mean        SD  N            Mean ± SD
0   DNN  Precision_weighted  0.979619  0.011494  5  0.979619 ± 0.011494
1   DNN     Recall_weighted  0.974942  0.011434  5  0.974942 ± 0.011434
2   DNN         F1_weighted  0.976559  0.012063  5  0.976559 ± 0.012063
3   DNN        FPR_weighted  0.027090  0.031473  5  0.027090 ± 0.031473

Representative run:

,Model,Representative_Run,Representative_Seed,Representative_F1_macro,Five_Run_Mean_F1_macro
0,DNN,1,42,0.658919,0.655815

All outputs saved to: /kaggle/working/Baseline_Balanced_Without_FA_CICIoT2023_DNN_5_seed_results

## 8. Reload a saved DNN baseline without retraining

In [13]:
def load_saved_baseline_bundle(run_number, seed, output_directory=OUTPUT_DIRECTORY):
    """Reload one trained baseline model together with fixed preprocessing."""
    output_directory = Path(output_directory)
    seed_directory = output_directory / f"DNN_Seed_{run_number}"
    model_path = seed_directory / f"dnn_seed_{seed}.keras"
    if not model_path.exists():
        raise FileNotFoundError(f"Saved model not found: {model_path}")

    artifact_directory = output_directory / "reusable_artifacts"
    with (artifact_directory / "feature_columns.json").open("r", encoding="utf-8") as f:
        saved_feature_columns = json.load(f)

    return {
        "model_name": "DNN",
        "run_number": int(run_number),
        "seed": int(seed),
        "model": load_model(model_path),
        "scaler": joblib.load(artifact_directory / "standard_scaler.joblib"),
        "label_encoder": joblib.load(artifact_directory / "label_encoder.joblib"),
        "feature_columns": saved_feature_columns,
        "model_path": model_path,
    }


def predict_with_saved_baseline(raw_features, bundle):
    if not isinstance(raw_features, pd.DataFrame):
        raw_features = pd.DataFrame(raw_features, columns=bundle["feature_columns"])

    missing = [c for c in bundle["feature_columns"] if c not in raw_features.columns]
    if missing:
        raise KeyError(f"Missing required features: {missing}")

    ordered = raw_features[bundle["feature_columns"]]
    scaled = bundle["scaler"].transform(ordered).astype(np.float32)

    if bundle["model_name"] in {"LSTM", "GRU"}:
        scaled = scaled.reshape(-1, 1, len(bundle["feature_columns"]))

    probabilities = bundle["model"].predict(scaled, verbose=0)
    predicted_codes = np.argmax(probabilities, axis=1)
    predicted_labels = bundle["label_encoder"].inverse_transform(predicted_codes)

    predictions = pd.DataFrame({
        "Predicted_Code": predicted_codes,
        "Predicted_Label": predicted_labels,
        "Maximum_Probability": probabilities.max(axis=1),
    }, index=raw_features.index)
    return predictions, probabilities

In [12]:
import shutil

# Compress the entire Kaggle working/output directory
shutil.make_archive(
    "/kaggle/working/BaslineBalancedCICIoT2023_DNN-5_Seed_V3",
    "zip",
    "/kaggle/working"
)

print("Created: /kaggle/working/BaslineBalancedCICIoT2023_DNN-5_Seed_V3.zip")

Created: /kaggle/working/BaslineBalancedCICIoT2023_DNN-5_Seed_V3.zip